// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | VideosSlice
  | TalksSlice
  | RichtextSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Talk documents
 */
interface TalkDocumentData {
  /**
   * Date field in *Talk*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * talk field in *Talk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.talk
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  talk: prismic.KeyTextField;

  /**
   * conference field in *Talk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.conference
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  conference: prismic.KeyTextField;

  /**
   * location field in *Talk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * link field in *Talk*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Talk document from Prismic
 *
 * - **API ID**: `talk`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TalkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TalkDocumentData>, "talk", Lang>;

/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Video*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: video.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Description field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * videoId field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.videoid
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videoid: prismic.KeyTextField;

  /**
   * Image field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image: prismic.KeyTextField;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VideoDocumentData>, "video", Lang>;

export type AllDocumentTypes = PageDocument | TalkDocument | VideoDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title Tag field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h1
   * - **API ID Path**: hero.default.primary.title_tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  title_tag: prismic.SelectField<"h1" | "h2" | "h3" | "p", "filled">;

  /**
   * Sub Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Sub Title Tag field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_title_tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sub_title_tag: prismic.SelectField<"h1" | "h2" | "h3" | "p">;

  /**
   * Right field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.right
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  right: prismic.BooleanField;

  /**
   * Smaller Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.smaller_title
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  smaller_title: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Richtext → Default → Primary*
 */
export interface RichtextSliceDefaultPrimary {
  /**
   * body field in *Richtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Richtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichtextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Richtext*
 */
type RichtextSliceVariation = RichtextSliceDefault;

/**
 * Richtext Shared Slice
 *
 * - **API ID**: `richtext`
 * - **Description**: Richtext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichtextSlice = prismic.SharedSlice<
  "richtext",
  RichtextSliceVariation
>;

/**
 * Primary content in *Talks → Default → Primary*
 */
export interface TalksSliceDefaultPrimary {
  /**
   * Title field in *Talks → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talks.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Small field in *Talks → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: talks.default.primary.small
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  small: prismic.BooleanField;

  /**
   * Limit field in *Talks → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: talks.default.primary.limit
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  limit: prismic.NumberField;
}

/**
 * Default variation for Talks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TalksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Talks*
 */
type TalksSliceVariation = TalksSliceDefault;

/**
 * Talks Shared Slice
 *
 * - **API ID**: `talks`
 * - **Description**: Talks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalksSlice = prismic.SharedSlice<"talks", TalksSliceVariation>;

/**
 * Primary content in *Videos → Default → Primary*
 */
export interface VideosSliceDefaultPrimary {
  /**
   * Title field in *Videos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Videos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Extras URL field in *Videos → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.extras_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  extras_url: prismic.LinkField;

  /**
   * Small field in *Videos → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: videos.default.primary.small
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  small: prismic.BooleanField;

  /**
   * firstFeatured field in *Videos → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: videos.default.primary.firstfeatured
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  firstfeatured: prismic.BooleanField;

  /**
   * Limit field in *Videos → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.limit
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  limit: prismic.NumberField;

  /**
   * Tag field in *Videos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Default variation for Videos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Videos*
 */
type VideosSliceVariation = VideosSliceDefault;

/**
 * Videos Shared Slice
 *
 * - **API ID**: `videos`
 * - **Description**: Videos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSlice = prismic.SharedSlice<"videos", VideosSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TalkDocument,
      TalkDocumentData,
      VideoDocument,
      VideoDocumentData,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichtextSlice,
      RichtextSliceDefaultPrimary,
      RichtextSliceVariation,
      RichtextSliceDefault,
      TalksSlice,
      TalksSliceDefaultPrimary,
      TalksSliceVariation,
      TalksSliceDefault,
      VideosSlice,
      VideosSliceDefaultPrimary,
      VideosSliceVariation,
      VideosSliceDefault,
    };
  }
}
